jobs:
  maven-central:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Set $JAVA_11_HOME
      run: echo "JAVA_11_HOME=$JAVA_HOME" >> $GITHUB_ENV
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Set $JAVA_8_HOME
      run: echo "JAVA_8_HOME=$JAVA_HOME" >> $GITHUB_ENV
    - continue-on-error: true
      name: Validate gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      name: Run checks
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: check
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_PASSWORD }}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      name: Publish to Maven Central
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
name: Publish
on:
  repository_dispatch:
    types: trigger-ga___publish.yml
